project_id = "hrgpnotiuiaioadrziuz"

[functions.hydra-orchestrator]
verify_jwt = false

[functions.hydra-stream]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.flow-runtime]
verify_jwt = false

[functions.flow-logistics]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false
